name: "Credo"
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  dialyzer:
    name: Run Credo
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: erlef/setup-beam@v1
        with:
          otp-version: "26"
          elixir-version: "1.16"

      - name: mix-cache
        uses: actions/cache@v3
        id: mix-cache
        with:
          path: |
            deps
            _build
          key: ${{ runner.os }}-26-1.16-${{ hashFiles('mix.lock') }}

      - name: mix local
        run: |
          mix local.rebar --force
          mix local.hex --force

      - name: mix compile
        run: |
          mix deps.get
          mix deps.compile
          mix compile
        if: steps.mix-cache.outputs.cache-hit != 'true'

      - name: mix credo
        run: mix credo --strict --all
